Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: VerticaAthenaConnectorTest1
    Description: verticaAthenaConnector Description
    Author: default author
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://test-connector-west/f2192c03aa492ef2104991bb8be53aba
    ReadmeUrl: s3://test-connector-west/e2a58254d669a0583916d6f5fa17aa61
    Labels:
    - athena-federation
    HomePageUrl: https://github.com/awslabs/aws-athena-query-federation
    SemanticVersion: 2021.24.30
    SourceCodeUrl: https://github.com/awslabs/aws-athena-query-federation
Parameters:
  AthenaCatalogName:
    Description: The name you will give to this catalog in Athena. It will also be
      used as the function name. This name must satisfy the pattern ^[a-z0-9-_]{1,64}$
    Type: String
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  SpillBucket:
    Description: The name of the bucket where this function can spill data.
    Type: String
  VerticaExportBucket:
    Description: The bucket where the Vertica Query results will be exported.
    Type: String
  SpillPrefix:
    Description: The prefix within SpillBucket where this function can spill data.
    Type: String
    Default: athena-spill
  LambdaTimeout:
    Description: Maximum Lambda invocation runtime in seconds. (min 1 - 900 max)
    Default: 900
    Type: Number
  LambdaMemory:
    Description: Lambda memory in MB (min 128 - 3008 max).
    Default: 3008
    Type: Number
  DisableSpillEncryption:
    Description: 'WARNING: If set to ''true'' encryption for spilled data is disabled.'
    Default: 'false'
    Type: String
  SecretNameOrPrefix:
    Description: The name or prefix of a set of names within Secrets Manager that
      this function should have access to. (e.g. vertica-*).
    Type: String
    Default: vertica-*
  VerticaConnectionString:
    Description: The Vertica connection details to use by default if not catalog specific
      connection is defined and optionally using SecretsManager (e.g. ${secret_name}).
    Type: String
    Default: jdbc:vertica://<host_name>:<port>/<database>?user=${vertica-username}&password=${vertica-password}
Resources:
  ConnectorConfig:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          disable_spill_encryption:
            Ref: DisableSpillEncryption
          spill_bucket:
            Ref: SpillBucket
          spill_prefix:
            Ref: SpillPrefix
          export_bucket:
            Ref: VerticaExportBucket
          default_vertica:
            Ref: VerticaConnectionString
      FunctionName:
        Fn::Sub: ${AthenaCatalogName}
      Handler: com.amazonaws.connectors.athena.vertica.VerticaCompositeHandler
      CodeUri: s3://test-connector-west/5a2e0bba3a18a7e1c5243a5c3736087a
      Description: Amazon Athena Vertica Connector
      Runtime: java8
      Timeout:
        Ref: LambdaTimeout
      MemorySize:
        Ref: LambdaMemory
      Policies:
      - Statement:
        - Action:
          - athena:GetQueryExecution
          - s3:ListAllMyBuckets
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - s3:ListBucket
          Effect: Allow
          Resource:
          - Fn::Sub: arn:aws:s3:::${VerticaExportBucket}
          - Fn::Sub: arn:aws:s3:::${SpillBucket}
        Version: '2012-10-17'
      - Statement:
        - Action:
          - secretsmanager:GetSecretValue
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:secretsmanager:*:*:secret:${SecretNameOrPrefix}
      - S3ReadPolicy:
          BucketName:
            Ref: SpillBucket
      - S3WritePolicy:
          BucketName:
            Ref: SpillBucket
      - S3ReadPolicy:
          BucketName:
            Ref: VerticaExportBucket
      - S3WritePolicy:
          BucketName:
            Ref: VerticaExportBucket
